/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.modules.Menu_config.View;

import framework.modules.Menu_config.Model.files_config.BLL.BLL_config;

/**
 *
 * @author pelu
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    public Config() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_date = new javax.swing.ButtonGroup();
        bg_currency = new javax.swing.ButtonGroup();
        bg_decimals = new javax.swing.ButtonGroup();
        bg_lang = new javax.swing.ButtonGroup();
        bg_theme = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jt_options = new javax.swing.JTabbedPane();
        jp_date = new javax.swing.JPanel();
        jl_date = new javax.swing.JLabel();
        jrb_date1 = new javax.swing.JRadioButton();
        jrb_date2 = new javax.swing.JRadioButton();
        jrb_date3 = new javax.swing.JRadioButton();
        jrb_date4 = new javax.swing.JRadioButton();
        jp_currency = new javax.swing.JPanel();
        jrb_euro = new javax.swing.JRadioButton();
        jrb_dolar = new javax.swing.JRadioButton();
        jrb_libra = new javax.swing.JRadioButton();
        jp_decimals = new javax.swing.JPanel();
        jrb_decimals1 = new javax.swing.JRadioButton();
        jrb_decimals2 = new javax.swing.JRadioButton();
        jrb_decimals3 = new javax.swing.JRadioButton();
        jp_language = new javax.swing.JPanel();
        jrb_eng = new javax.swing.JRadioButton();
        jrb_esp = new javax.swing.JRadioButton();
        jrb_val = new javax.swing.JRadioButton();
        jp_theme = new javax.swing.JPanel();
        jrb_theme1 = new javax.swing.JRadioButton();
        jrb_theme2 = new javax.swing.JRadioButton();
        jrb_theme3 = new javax.swing.JRadioButton();
        jrb_theme4 = new javax.swing.JRadioButton();
        jp_butons = new javax.swing.JPanel();
        jb_save = new javax.swing.JButton();
        jb_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_date.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jl_date.setText("Select a format to date fields:");

        bg_date.add(jrb_date1);
        jrb_date1.setSelected(true);
        jrb_date1.setText("dd/MM/yyyy");

        bg_date.add(jrb_date2);
        jrb_date2.setText("dd-MM-yyyy");

        bg_date.add(jrb_date3);
        jrb_date3.setText("yyyy/MM/dd");

        bg_date.add(jrb_date4);
        jrb_date4.setText("yyyy-MM-dd");

        javax.swing.GroupLayout jp_dateLayout = new javax.swing.GroupLayout(jp_date);
        jp_date.setLayout(jp_dateLayout);
        jp_dateLayout.setHorizontalGroup(
            jp_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_dateLayout.createSequentialGroup()
                .addGroup(jp_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_dateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_dateLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jp_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrb_date2)
                            .addComponent(jrb_date1))
                        .addGap(79, 79, 79)
                        .addGroup(jp_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_date3)
                            .addComponent(jrb_date4))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jp_dateLayout.setVerticalGroup(
            jp_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_dateLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_date1)
                    .addComponent(jrb_date3))
                .addGap(32, 32, 32)
                .addGroup(jp_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_date2)
                    .addComponent(jrb_date4))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jt_options.addTab("Date", jp_date);

        bg_currency.add(jrb_euro);
        jrb_euro.setSelected(true);
        jrb_euro.setText("Euros");

        bg_currency.add(jrb_dolar);
        jrb_dolar.setText("Dolars");

        bg_currency.add(jrb_libra);
        jrb_libra.setText("Libra");

        javax.swing.GroupLayout jp_currencyLayout = new javax.swing.GroupLayout(jp_currency);
        jp_currency.setLayout(jp_currencyLayout);
        jp_currencyLayout.setHorizontalGroup(
            jp_currencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_currencyLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jp_currencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_libra)
                    .addComponent(jrb_dolar)
                    .addComponent(jrb_euro))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jp_currencyLayout.setVerticalGroup(
            jp_currencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_currencyLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jrb_euro)
                .addGap(18, 18, 18)
                .addComponent(jrb_dolar)
                .addGap(18, 18, 18)
                .addComponent(jrb_libra)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jt_options.addTab("Curency", jp_currency);

        bg_decimals.add(jrb_decimals1);
        jrb_decimals1.setText("1 decimal");

        bg_decimals.add(jrb_decimals2);
        jrb_decimals2.setSelected(true);
        jrb_decimals2.setText("2 decimals");

        bg_decimals.add(jrb_decimals3);
        jrb_decimals3.setText("3 decimals");

        javax.swing.GroupLayout jp_decimalsLayout = new javax.swing.GroupLayout(jp_decimals);
        jp_decimals.setLayout(jp_decimalsLayout);
        jp_decimalsLayout.setHorizontalGroup(
            jp_decimalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_decimalsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jp_decimalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_decimals3)
                    .addComponent(jrb_decimals2)
                    .addComponent(jrb_decimals1))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jp_decimalsLayout.setVerticalGroup(
            jp_decimalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_decimalsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jrb_decimals1)
                .addGap(18, 18, 18)
                .addComponent(jrb_decimals2)
                .addGap(18, 18, 18)
                .addComponent(jrb_decimals3)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jt_options.addTab("Decimals", jp_decimals);

        bg_lang.add(jrb_eng);
        jrb_eng.setSelected(true);
        jrb_eng.setText("English");

        bg_lang.add(jrb_esp);
        jrb_esp.setText("Spanish");

        bg_lang.add(jrb_val);
        jrb_val.setText("Valencian");

        javax.swing.GroupLayout jp_languageLayout = new javax.swing.GroupLayout(jp_language);
        jp_language.setLayout(jp_languageLayout);
        jp_languageLayout.setHorizontalGroup(
            jp_languageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_languageLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jp_languageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_val)
                    .addComponent(jrb_esp)
                    .addComponent(jrb_eng))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jp_languageLayout.setVerticalGroup(
            jp_languageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_languageLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jrb_eng)
                .addGap(18, 18, 18)
                .addComponent(jrb_esp)
                .addGap(18, 18, 18)
                .addComponent(jrb_val)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jt_options.addTab("Language", jp_language);

        bg_theme.add(jrb_theme1);
        jrb_theme1.setText("Metal");

        bg_theme.add(jrb_theme2);
        jrb_theme2.setText("Windows");

        bg_theme.add(jrb_theme3);
        jrb_theme3.setText("Motif");

        bg_theme.add(jrb_theme4);
        jrb_theme4.setSelected(true);
        jrb_theme4.setText("Nimbus");

        javax.swing.GroupLayout jp_themeLayout = new javax.swing.GroupLayout(jp_theme);
        jp_theme.setLayout(jp_themeLayout);
        jp_themeLayout.setHorizontalGroup(
            jp_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_themeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jp_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_theme1)
                    .addComponent(jrb_theme2))
                .addGap(40, 40, 40)
                .addGroup(jp_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_theme3)
                    .addComponent(jrb_theme4))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jp_themeLayout.setVerticalGroup(
            jp_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_themeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jp_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_theme1)
                    .addComponent(jrb_theme3))
                .addGap(36, 36, 36)
                .addGroup(jp_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_theme2)
                    .addComponent(jrb_theme4))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jt_options.addTab("Theme", jp_theme);

        jb_save.setText("Save");

        jb_back.setText("Back");

        javax.swing.GroupLayout jp_butonsLayout = new javax.swing.GroupLayout(jp_butons);
        jp_butons.setLayout(jp_butonsLayout);
        jp_butonsLayout.setHorizontalGroup(
            jp_butonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_butonsLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jb_save, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_butonsLayout.setVerticalGroup(
            jp_butonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_butonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_butonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_save)
                    .addComponent(jb_back))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_butons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jt_options)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jt_options)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_butons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Config().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_currency;
    private javax.swing.ButtonGroup bg_date;
    private javax.swing.ButtonGroup bg_decimals;
    private javax.swing.ButtonGroup bg_lang;
    private javax.swing.ButtonGroup bg_theme;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_back;
    public javax.swing.JButton jb_save;
    private javax.swing.JLabel jl_date;
    private javax.swing.JPanel jp_butons;
    private javax.swing.JPanel jp_currency;
    private javax.swing.JPanel jp_date;
    private javax.swing.JPanel jp_decimals;
    private javax.swing.JPanel jp_language;
    private javax.swing.JPanel jp_theme;
    public static javax.swing.JRadioButton jrb_date1;
    public static javax.swing.JRadioButton jrb_date2;
    public static javax.swing.JRadioButton jrb_date3;
    public static javax.swing.JRadioButton jrb_date4;
    public static javax.swing.JRadioButton jrb_decimals1;
    public static javax.swing.JRadioButton jrb_decimals2;
    public static javax.swing.JRadioButton jrb_decimals3;
    public static javax.swing.JRadioButton jrb_dolar;
    public static javax.swing.JRadioButton jrb_eng;
    public static javax.swing.JRadioButton jrb_esp;
    public static javax.swing.JRadioButton jrb_euro;
    public static javax.swing.JRadioButton jrb_libra;
    public static javax.swing.JRadioButton jrb_theme1;
    public static javax.swing.JRadioButton jrb_theme2;
    public static javax.swing.JRadioButton jrb_theme3;
    public static javax.swing.JRadioButton jrb_theme4;
    public static javax.swing.JRadioButton jrb_val;
    private javax.swing.JTabbedPane jt_options;
    // End of variables declaration//GEN-END:variables
}
