package framework.modules.Menu_config.View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pelu
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        //setLayout(new BorderLayout());
        //setContentPane(new JLabel(new ImageIcon(singleton.fondo_menu)));
        //setLayout(new FlowLayout());
        
        initComponents();
//        this.setTitle("APP");
//        Image icono=Toolkit.getDefaultToolkit().getImage(singleton.icon_app);
//	this.setIconImage(icono);
//	this.setLocationRelativeTo(null);
//	this.setSize(680,450);//ancho x alto
//	this.setResizable(false);
//	
//	//this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        
//        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//		addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosing(WindowEvent e) {
//                JOptionPane.showMessageDialog(null,"Saliendo de la aplicación");
//                dispose();
//                System.exit(0);
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_admin = new javax.swing.JButton();
        jb_reg_user = new javax.swing.JButton();
        jb_client = new javax.swing.JButton();
        jl_config = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_admin.setBackground(new java.awt.Color(0, 204, 204));
        jb_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/icon_user.png"))); // NOI18N
        jb_admin.setText("Admin");

        jb_reg_user.setBackground(new java.awt.Color(0, 204, 204));
        jb_reg_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/icon_user.png"))); // NOI18N
        jb_reg_user.setText("Reg. User");

        jb_client.setBackground(new java.awt.Color(0, 204, 204));
        jb_client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/icon_user.png"))); // NOI18N
        jb_client.setText("Client");

        jl_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/setting.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jb_client, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_reg_user, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jl_config, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jl_config)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jb_client, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jb_reg_user, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_admin;
    public javax.swing.JButton jb_client;
    public javax.swing.JButton jb_reg_user;
    public javax.swing.JLabel jl_config;
    // End of variables declaration//GEN-END:variables
}
