/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.modules.users.View.Client;

import framework.classes.class_date;
import framework.modules.users.View.Admin.*;
import framework.modules.Menu.View.menu;
import framework.modules.users.Model.utils_users.core_date;
import framework.modules.users.Model.utils_users.core_funtions;
import static framework.modules.users.View.Admin.admin_create.jt_dni;
import static framework.modules.users.View.Admin.admin_create.jt_name;
import framework.utils.validate;
import java.awt.Color;
import static java.awt.Color.GREEN;
import static java.awt.Color.RED;
import static java.awt.Color.WHITE;
import static java.awt.Color.black;
import java.awt.Image;
import static java.awt.SystemColor.menu;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pelu
 */
public class client_form extends javax.swing.JFrame {

    /**
     * Creates new form admin_form
     */
    public client_form() {
        initComponents();
        this.setTitle("Create client");
	this.setLocationRelativeTo(null);
	this.setSize(550,400);//ancho x alto
	this.setResizable(false);
        
	//Image icono=Toolkit.getDefaultToolkit().getImage("p1.jpg");
	//this.setIconImage(icono);
	//this.setExtendedState(JFrame.MAXIMIZED_BOTH); //la aplicación se abre maximizada
        
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JOptionPane.showMessageDialog(null,"Saliendo de la aplicación");
                dispose();
                System.exit(0);
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField10 = new javax.swing.JTextField();
        bgr_state = new javax.swing.ButtonGroup();
        brg_premium = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jsc_form = new javax.swing.JScrollPane();
        create_form = new javax.swing.JPanel();
        lb_dni = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        lb_surname = new javax.swing.JLabel();
        lb_mobile = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        lb_nick = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        lb_avatar = new javax.swing.JLabel();
        lb_birthday = new javax.swing.JLabel();
        lb_update = new javax.swing.JLabel();
        lb_shopping = new javax.swing.JLabel();
        jt_dni = new javax.swing.JTextField();
        jt_name = new javax.swing.JTextField();
        jt_surname = new javax.swing.JTextField();
        jt_mobile = new javax.swing.JTextField();
        jt_email = new javax.swing.JTextField();
        jt_nick = new javax.swing.JTextField();
        jt_avatar = new javax.swing.JTextField();
        jt_shopping = new javax.swing.JTextField();
        lb_state = new javax.swing.JLabel();
        jrb_conected = new javax.swing.JRadioButton();
        jrb_disconected = new javax.swing.JRadioButton();
        jdc_birthday = new com.toedter.calendar.JDateChooser();
        jdc_update = new com.toedter.calendar.JDateChooser();
        check_dni = new javax.swing.JLabel();
        check_name = new javax.swing.JLabel();
        check_surname = new javax.swing.JLabel();
        check_mobile = new javax.swing.JLabel();
        check_email = new javax.swing.JLabel();
        check_nick = new javax.swing.JLabel();
        check_password = new javax.swing.JLabel();
        check_avatar = new javax.swing.JLabel();
        check_birthday = new javax.swing.JLabel();
        check_dontract = new javax.swing.JLabel();
        check_shopping = new javax.swing.JLabel();
        jb_avatar = new javax.swing.JButton();
        jt_password = new javax.swing.JPasswordField();
        chb_password = new javax.swing.JCheckBox();
        jrb_yes = new javax.swing.JRadioButton();
        jrb_no = new javax.swing.JRadioButton();
        jl_premium = new javax.swing.JLabel();
        jl_type = new javax.swing.JLabel();
        jt_type = new javax.swing.JTextField();
        check_type = new javax.swing.JLabel();
        jl_back = new javax.swing.JLabel();
        jb_create = new javax.swing.JButton();
        jb_clean = new javax.swing.JButton();
        jl_alert = new javax.swing.JLabel();

        jTextField10.setText("jTextField10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 400));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 24)); // NOI18N
        jLabel1.setText("Create client");

        jsc_form.setHorizontalScrollBar(null);

        create_form.setPreferredSize(new java.awt.Dimension(491, 700));

        lb_dni.setText("ID Card:");

        lb_name.setText("Name:");

        lb_surname.setText("Surmane/s:");

        lb_mobile.setText("Mobile:");

        lb_email.setText("Email:");

        lb_nick.setText("Nick Name:");

        lb_password.setText("Password:");

        lb_avatar.setText("Avatar:");

        lb_birthday.setText("Bithday date:");

        lb_update.setText("Up date");

        lb_shopping.setText("Shopping:");

        jt_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_dniKeyPressed(evt);
            }
        });

        jt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_nameKeyPressed(evt);
            }
        });

        jt_surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_surnameKeyPressed(evt);
            }
        });

        jt_mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_mobileKeyPressed(evt);
            }
        });

        jt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_emailKeyPressed(evt);
            }
        });

        jt_nick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_nickKeyPressed(evt);
            }
        });

        jt_shopping.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_shoppingKeyPressed(evt);
            }
        });

        lb_state.setText("State:");

        bgr_state.add(jrb_conected);
        jrb_conected.setSelected(true);
        jrb_conected.setText("Connected");
        jrb_conected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_conectedActionPerformed(evt);
            }
        });

        bgr_state.add(jrb_disconected);
        jrb_disconected.setText("Disconnected");
        jrb_disconected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_disconectedActionPerformed(evt);
            }
        });

        jdc_birthday.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdc_birthdayPropertyChange(evt);
            }
        });

        jb_avatar.setText("Select");

        jt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_passwordKeyReleased(evt);
            }
        });

        chb_password.setText("See the password");

        brg_premium.add(jrb_yes);
        jrb_yes.setText("Yes");
        jrb_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_yesActionPerformed(evt);
            }
        });

        brg_premium.add(jrb_no);
        jrb_no.setSelected(true);
        jrb_no.setText("No");

        jl_premium.setText("Premium:");

        jl_type.setText("Type:");

        jt_type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_typeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout create_formLayout = new javax.swing.GroupLayout(create_form);
        create_form.setLayout(create_formLayout);
        create_formLayout.setHorizontalGroup(
            create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lb_surname)
                    .addComponent(lb_mobile)
                    .addComponent(lb_email)
                    .addComponent(lb_nick)
                    .addComponent(lb_password)
                    .addComponent(lb_avatar)
                    .addComponent(lb_shopping)
                    .addComponent(lb_state)
                    .addComponent(lb_update)
                    .addComponent(jl_premium)
                    .addComponent(lb_birthday)
                    .addComponent(jl_type))
                .addGap(34, 34, 34)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(create_formLayout.createSequentialGroup()
                        .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(create_formLayout.createSequentialGroup()
                                .addComponent(jrb_conected)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb_disconected)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, create_formLayout.createSequentialGroup()
                                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_dni)
                                    .addComponent(jt_name)
                                    .addComponent(jt_surname)
                                    .addComponent(jt_mobile, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(jt_email)
                                    .addComponent(jt_nick)
                                    .addComponent(jt_password)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, create_formLayout.createSequentialGroup()
                                        .addComponent(jdc_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, create_formLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(check_dontract, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(create_formLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(check_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jt_avatar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jt_shopping, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(create_formLayout.createSequentialGroup()
                                        .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chb_password)
                                            .addGroup(create_formLayout.createSequentialGroup()
                                                .addComponent(jrb_yes)
                                                .addGap(18, 18, 18)
                                                .addComponent(jrb_no)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jt_type))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(check_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(check_name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(check_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(check_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(check_email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(check_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(check_password, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(check_shopping, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(create_formLayout.createSequentialGroup()
                                        .addComponent(jb_avatar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(check_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(check_type, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(57, 57, 57))
                    .addGroup(create_formLayout.createSequentialGroup()
                        .addComponent(jdc_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        create_formLayout.setVerticalGroup(
            create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_formLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_dni)
                    .addComponent(jt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_name)
                    .addComponent(jt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_surname)
                    .addComponent(jt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_mobile)
                    .addComponent(jt_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_email)
                    .addComponent(jt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nick)
                    .addComponent(jt_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_password)
                    .addComponent(check_password, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(create_formLayout.createSequentialGroup()
                        .addComponent(jt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chb_password)))
                .addGap(18, 18, 18)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(create_formLayout.createSequentialGroup()
                        .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_avatar)
                            .addComponent(check_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb_conected)
                            .addComponent(jrb_disconected)
                            .addComponent(lb_state))
                        .addGap(18, 18, 18)
                        .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_birthday)
                            .addComponent(jdc_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(create_formLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_update)
                                    .addComponent(jdc_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(create_formLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(check_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(check_dontract, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jb_avatar))
                .addGap(18, 18, 18)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_shopping)
                    .addComponent(jt_shopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_shopping, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_premium)
                    .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrb_yes)
                        .addComponent(jrb_no)))
                .addGap(18, 18, 18)
                .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(create_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_type)
                        .addComponent(jt_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(check_type, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jsc_form.setViewportView(create_form);

        jl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/modules/users/img/back.png"))); // NOI18N
        jl_back.setText("Atras");
        jl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_backMouseClicked(evt);
            }
        });

        jb_create.setText("Create");

        jb_clean.setText("Clean");
        jb_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cleanActionPerformed(evt);
            }
        });

        jl_alert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsc_form, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(jl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jb_create, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jb_clean, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsc_form, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_create, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_clean, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jl_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_conectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_conectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_conectedActionPerformed

    private void jrb_disconectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_disconectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_disconectedActionPerformed
    
    private void jt_dniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_dniKeyPressed
       boolean check=false;
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jt_dni.getText().equals("")){
                check_dni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_dni.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }else{
                check=validate.validate_dni(jt_dni.getText());
     
                if(check==true){
                    check_dni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
                    jt_dni.setBackground(GREEN);
                    jl_alert.setText("");
                    jt_name.setText("");
                    jt_name.requestFocus();
                }else{
                    check_dni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                    jt_dni.setBackground(RED);
                    jl_alert.setText("The value isn't valid");
                }
            }
            
            
        }
    }//GEN-LAST:event_jt_dniKeyPressed

    private void jt_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_nameKeyPressed
       boolean check=false;
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jt_name.getText().equals("")){
                check_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_name.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }else{
                check=validate.validate_name(jt_name.getText());
     
                if(check==true){
                    check_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
                    jt_name.setBackground(GREEN);
                    jl_alert.setText("");
                    jt_surname.setText("");
                    jt_surname.requestFocus();
                }else{
                    check_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                    jt_name.setBackground(RED);
                    jl_alert.setText("The value isn't valid");
                }
            }
            
            
        } 
    }//GEN-LAST:event_jt_nameKeyPressed

    private void jt_surnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_surnameKeyPressed
        boolean check=false;
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jt_surname.getText().equals("")){
                check_surname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_surname.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }else{
                check=validate.validate_surname(jt_surname.getText());
     
                if(check==true){
                    check_surname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
                    jt_surname.setBackground(GREEN);
                    jl_alert.setText("");
                    jt_mobile.setText("");
                    jt_mobile.requestFocus();
                }else{
                    check_surname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                    jt_surname.setBackground(RED);
                    jl_alert.setText("The value isn't valid");
                }
            }
            
            
        } 
    }//GEN-LAST:event_jt_surnameKeyPressed

    private void jt_mobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_mobileKeyPressed
        boolean check=false;
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jt_mobile.getText().equals("")){
                check_mobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_mobile.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }
                check=validate.validate_mobile(jt_mobile.getText());
     
                if(check==true){
                    check_mobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
                    jt_mobile.setBackground(GREEN);
                    jl_alert.setText("");
                    jt_email.setText("");
                    jt_email.requestFocus();
                }else{
                    check_mobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                    jt_mobile.setBackground(RED);
                    jl_alert.setText("The value isn't valid");
                }
            
            
            
        }
    }//GEN-LAST:event_jt_mobileKeyPressed

    private void jt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_emailKeyPressed
        boolean check=false;
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jt_email.getText().equals("")){
                check_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_email.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }
                check=validate.validate_email(jt_email.getText());
     
                if(check==true){
                    check_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
                    jt_email.setBackground(GREEN);
                    jl_alert.setText("");
                    jt_nick.setText("");
                    jt_nick.requestFocus();
                }else{
                    check_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                    jt_email.setBackground(RED);
                    jl_alert.setText("The value isn't valid");
                }
            
            
            
        }
    }//GEN-LAST:event_jt_emailKeyPressed

    private void jt_nickKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_nickKeyPressed
        boolean check=false;
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jt_nick.getText().equals("")){
                check_nick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_nick.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }
                check=validate.validate_user(jt_nick.getText());
     
                if(check==true){
                    check_nick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
                    jt_nick.setBackground(GREEN);
                    jl_alert.setText("");
                    jt_password.setText("");
                    jt_password.requestFocus();
                }else{
                    check_nick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                    jt_nick.setBackground(RED);
                    jl_alert.setText("The value isn't valid");
                }  
        }
    }//GEN-LAST:event_jt_nickKeyPressed

    private void jt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_passwordKeyPressed
        boolean check=false;
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jt_password.getText().equals("")){
                check_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_password.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }
            
            check=validate.validate_password(jt_password.getText());
     
            if(check==true){
                check_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
                jt_password.setBackground(GREEN);
                jl_alert.setText("");
                jt_avatar.setText("");
                jt_avatar.requestFocus();
            }else{
                check_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_password.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }  
        }
    }//GEN-LAST:event_jt_passwordKeyPressed

    private void jt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_passwordKeyReleased
        
        if(chb_password.isSelected()){
            jt_password.setEchoChar((char)0);
        }else{
            jt_password.setEchoChar('*');
        }
        
    }//GEN-LAST:event_jt_passwordKeyReleased

    private void jl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_backMouseClicked
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_backMouseClicked

    private void jt_shoppingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_shoppingKeyPressed
        boolean check=false;
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jt_shopping.getText().equals("")){
                check_shopping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_shopping.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }
            
            check=validate.validate_shopping(jt_shopping.getText());
     
            if(check==true){
                check_shopping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
                jt_shopping.setBackground(GREEN);
                jl_alert.setText("");
            }else{
                check_shopping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_shopping.setBackground(RED);
                jl_alert.setText("The value isn't valid");
            }  
        }
    }//GEN-LAST:event_jt_shoppingKeyPressed

    private void jrb_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_yesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_yesActionPerformed

    private void jt_typeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_typeKeyPressed
        boolean check=false;
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jt_type.getText().equals("")){
                check_type.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_type.setBackground(RED);
            }
            
            check=validate.validate_type(jt_type.getText());
     
            if(check==true){
                check_type.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
                jt_type.setBackground(GREEN);
            }else{
                check_type.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
                jt_type.setBackground(RED);
            }  
        }
    }//GEN-LAST:event_jt_typeKeyPressed

    private void jb_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cleanActionPerformed
        jt_dni.setText("");
        jt_dni.setBackground(WHITE);
        check_dni.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jt_name.setText("");
        jt_name.setBackground(WHITE);
        check_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jt_surname.setText("");
        jt_surname.setBackground(WHITE);
        check_surname.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jt_mobile.setText("");
        jt_mobile.setBackground(WHITE);
        check_mobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jt_email.setText("");
        jt_email.setBackground(WHITE);
        check_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jt_nick.setText("");
        jt_nick.setBackground(WHITE);
        check_nick.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jt_password.setText("");
        jt_password.setBackground(WHITE);
        check_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jt_avatar.setText("");
        jt_avatar.setBackground(WHITE);
        check_avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jt_shopping.setText("");
        jt_shopping.setBackground(WHITE);
        check_shopping.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jt_type.setText("");
        jt_type.setBackground(WHITE);
        check_type.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        jrb_conected.setSelected(true);
        chb_password.setSelected(false);
    }//GEN-LAST:event_jb_cleanActionPerformed

    private void jdc_birthdayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdc_birthdayPropertyChange
        Calendar birthday;
        int day, month, year=0;
        class_date birth=null;
        //String dateformat="dd/MM/yyyy";
        String s="";
        boolean check=false;
        
        try{
            birthday=jdc_birthday.getCalendar();
            s=birthday.get(Calendar.DATE)+"/"+(birthday.get(Calendar.MONTH)+1)+"/"+birthday.get(Calendar.YEAR);
            birth=new class_date(s);
            check=core_date.restricted_years(birth, 16);
            
            if(check==false){
              check_birthday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
              jdc_birthday.setBackground(RED);  
            }else{
                jdc_birthday.setBackground(Color.green);
                check_birthday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/apply.png")));
            }
            
        }catch(Exception e){
            //check_birthday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/cancel.png")));
            //jdc_birthday.setBackground(WHITE);
        }
    }//GEN-LAST:event_jdc_birthdayPropertyChange

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(admin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(admin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(admin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(admin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new admin_form().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgr_state;
    private javax.swing.ButtonGroup brg_premium;
    private javax.swing.JCheckBox chb_password;
    private javax.swing.JLabel check_avatar;
    private javax.swing.JLabel check_birthday;
    private javax.swing.JLabel check_dni;
    private javax.swing.JLabel check_dontract;
    private javax.swing.JLabel check_email;
    private javax.swing.JLabel check_mobile;
    private javax.swing.JLabel check_name;
    private javax.swing.JLabel check_nick;
    private javax.swing.JLabel check_password;
    private javax.swing.JLabel check_shopping;
    private javax.swing.JLabel check_surname;
    private javax.swing.JLabel check_type;
    private javax.swing.JPanel create_form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JButton jb_avatar;
    private javax.swing.JButton jb_clean;
    private javax.swing.JButton jb_create;
    private com.toedter.calendar.JDateChooser jdc_birthday;
    private com.toedter.calendar.JDateChooser jdc_update;
    private javax.swing.JLabel jl_alert;
    private javax.swing.JLabel jl_back;
    private javax.swing.JLabel jl_premium;
    private javax.swing.JLabel jl_type;
    private javax.swing.JRadioButton jrb_conected;
    private javax.swing.JRadioButton jrb_disconected;
    private javax.swing.JRadioButton jrb_no;
    private javax.swing.JRadioButton jrb_yes;
    private javax.swing.JScrollPane jsc_form;
    private javax.swing.JTextField jt_avatar;
    public static javax.swing.JTextField jt_dni;
    private javax.swing.JTextField jt_email;
    private javax.swing.JTextField jt_mobile;
    public static javax.swing.JTextField jt_name;
    private javax.swing.JTextField jt_nick;
    private javax.swing.JPasswordField jt_password;
    private javax.swing.JTextField jt_shopping;
    private static javax.swing.JTextField jt_surname;
    private javax.swing.JTextField jt_type;
    private javax.swing.JLabel lb_avatar;
    private javax.swing.JLabel lb_birthday;
    private javax.swing.JLabel lb_dni;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_mobile;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_nick;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_shopping;
    private javax.swing.JLabel lb_state;
    private javax.swing.JLabel lb_surname;
    private javax.swing.JLabel lb_update;
    // End of variables declaration//GEN-END:variables
}
